# File: .azure/pipelines/ci.yaml
# Pipeline for the continuous integration to verify the changeset is good enuf,
# and has no platform specific content included.

# HINT: PR triggers are setup in the branch policies.
#       Learn more https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#pr-triggers
trigger: none

variables:
  vmImageName: ubuntu-latest

stages:
- stage: Build
  displayName: Build

  jobs:

  # HINT: Ensure everything's platform independent, 
  #       which means there's nothing Windows-specific has added.
  - job: Build
    pool: 
      vmImage: $(vmImageName)

    steps:
    - template: /.azure/pipelines/build/build-ci.yml
