# File: .azure/pipelines/deploy/release-rm.yml
# Deployment strategy and the steps to publish the function app.

parameters:
  vmImage: default
  subscription: default
  appName: default
  resourceGroup: default
  environment: default
  connectedService: default
  location: default

jobs:
- deployment: Deployment
  displayName: "Deploy to ${{ parameters.environment }}"
  
  environment: '${{ parameters.environment }}'
  
  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    runOnce:
      deploy:

        steps:
        - task: colinsalmcorner.colinsalmcorner-buildtasks.replace-tokens-task.ReplaceTokens@1
          displayName: 'Replace tokens in Application Parameters'
          inputs:
            sourcePath: '$(Pipeline.Workspace)/drop'
            filePattern: '*.json'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template deployment: Subscription scope | Resource.Functions.json'
          inputs:
            connectedServiceName: '${{ parameters.connectedService }}'
            deploymentScope: Subscription
            location: ${{ parameters.location }}
            csmFile: '$(Pipeline.Workspace)/drop/Resource.Functions.json'
            csmParametersFile: '$(Pipeline.Workspace)/drop/Param.Functions.${{ lower(parameters.environment) }}.json'
            
        - task: azureFunctionApp@1
          displayName: 'Azure functions app deploy to ${{ parameters.environment }}'
          inputs:
            azureSubscription: '${{ parameters.subscription }}'
            appType: functionApp
            appName: '${{ parameters.appName }}'
            package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
            resourceGroupName: '${{ parameters.resourceGroup }}'

        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'ARM Template deployment: Subscription scope | Resource.ApiManagement.json'
          inputs:
            connectedServiceName: '${{ parameters.connectedService }}'
            deploymentScope: Subscription
            location: ${{ parameters.location }}
            csmFile: '$(Pipeline.Workspace)/drop/Resource.ApiManagement.json'
            csmParametersFile: '$(Pipeline.Workspace)/drop/Param.ApiManagement.${{ lower(parameters.environment) }}.json'